add trait promotion without array
JuliaGeo/GeoInterface.jl pull request #159
Opened 2024-09-21 15:17 UTC by alex-s-gardner

This address #157

2024-09-21 15:31 UTC, rafaqz commented
Perfect, just needs a test

2024-09-22 06:53 UTC, rafaqz approved these changes

2024-09-22 06:58 UTC, rafaqz requested changes

2024-09-22 06:58 UTC, rafaqz commented on src/wrappers.jl
> +function FeatureCollection(fc::Feature; crs=crs(fc), extent=extent(fc))
Actually this isn't quite right. Instead you want to check `isfeature` in the method below

2024-09-23 16:52 UTC, asinghvi17 commented on src/wrappers.jl
> +end
```suggestion
```

2024-09-23 17:38 UTC, rafaqz commented on src/wrappers.jl
> +            isnothing(extent) ? (@__MODULE__).extent(parent) : extent
```suggestion
        FeatureCollection(
            [parent], 
            isnothing(crs) ? Wrappers.crs(parent) : crs, 
            isnothing(extent) ? Wrappers.extent(parent) : extent
```

2024-09-23 17:41 UTC, asinghvi17 commented on src/wrappers.jl
> +            isnothing(extent) ? (@__MODULE__).extent(parent) : extent
Ah that's a lot simpler

2024-09-23 17:42 UTC, rafaqz approved these changes

2024-09-23 17:53 UTC, merged

2024-09-23 17:53 UTC, asinghvi17 commented
Should we bump and release?