add getpolygons and getrings functions
JuliaGeo/GeoInterface.jl pull request #47
Opened 2022-05-01 05:51 UTC by rafaqz

This PR adds `getpolygons` and `getrings` functions to allow efficient access to all poylgons and rings in cases like Shapefile.jl where exterior and holes are not clearly separated in the spec. Packages like Rasters.jl don't actually care if they are separated so loading them all direstly is much more efficient. 

The fallback is to iterate over all polygons and rings.

2022-05-02 11:56 UTC, evetion commented
In the current documentation I had written:
> Where the getgeom could be an iterator (without the i) as well.

So that would be your functions, but without the `s` at the end. `getgeom(geom)` would give you an iterator and the first geom, which naturally falls back to the `getgeom(geom, i)` methods?

2022-05-02 17:18 UTC, rafaqz commented
Ah ok I messed that. Sounds good to me. We can do the same for `getring`.

2022-05-03 10:07 UTC, evetion commented
I've added iterators in the main pr https://github.com/JuliaGeo/GeoInterface.jl/pull/33/commits/1ba01f5c6f824ae1fe7509f17c9fd0016012a313. Only your `getrings(g::AbstractMultiPolygonTrait, geom) = (r for r in getrings(p) for p in getpolygons(geom))` that iterates over subgeometries as well is missing, as I think its better suited at ShapeFile itself?

2022-05-03 10:49 UTC, rafaqz commented
> I think its better suited at ShapeFile itself?

The idea is that Rasters.jl can call it without depending on Shapefile.jl, and `getring` still works for other types.

2022-05-03 11:21 UTC, rafaqz commented
Ok I've rebased and simplified this.

2022-05-03 11:36 UTC, evetion requested changes
The requested functionality is like adding flattening, but not completely, like coordinates, but over a single level. Should we make this consistent and also add getpoint/npoint for MultiLineStrings?

2022-05-03 11:36 UTC, evetion commented on src/defaults.jl
> +nring(p::AbstractPolygonTrait, geom) = sum(nring(p) for p in getpolygons(p))
```suggestion
nring(p::AbstractMultiPolygonTrait, geom) = sum(nring(p) for p in getpolygons(p))
```

2022-05-03 11:36 UTC, evetion commented on src/interface.jl
> +getpolygon(geom) = getpolygon(geomtype(geom), geom)
Duplicate of r332.

2022-05-03 11:36 UTC, evetion commented on src/interface.jl
> +"""
Complete duplication r200 onwards.

2022-05-03 17:16 UTC, rafaqz commented on src/interface.jl
> +"""
ahh ok rebase didn't work so well

2022-05-03 17:41 UTC, rafaqz commented
> Should we make this consistent and also add getpoint/npoint for MultiLineStrings?

Sure, then do we have to add it `getpoint` and `npoint` for `Polygon` and `MultiPolygon` too? (that works for me).

2022-05-03 18:13 UTC, rafaqz commented
Ok added `getpoint` everywhere it seems to makes sense, and standardised the iterator function docs.

2022-05-03 19:09 UTC, evetion commented
LGTM. If anything, I doubt about the `getpoint` on the `MultiPolygon` one, since that's three levels. But it still feels like a useful thing.

2022-05-03 19:09 UTC, merged