run jet and fix bugs
JuliaGeo/GeoInterface.jl pull request #74
Opened 2022-10-15 20:33 UTC by rafaqz

JET found a bunch of places we were not checking for zero length geoms. After fixing it still complains about some as it doesn't seem to see the runtime check on `npoint` means the iterator will never return `nothing`.

```julia
# Run from the GeoInteface environment
julia> JET.report_package(GeoInterface)
...
═════ 3 possible errors found ═════
┌ @ /home/raf/.julia/dev/GeoInterface/src/interface.jl:125 GeoInterface.issimple(geomtrait(geom), geom)
│┌ @ /home/raf/.julia/dev/GeoInterface/src/fallbacks.jl:90 GeoInterface.allunique(Base.Generator(#23, 1 GeoInterface.:(:) GeoInterface.npoint(t, geom) GeoInterface.:- 1))
││┌ @ set.jl:408 Base.indexed_iterate(x, 1)
│││┌ @ tuple.jl:91 x = iterate(I)
││││ no matching method found `iterate(::Nothing)`: x = iterate(I::Nothing)::Union{}
│││└───────────────
││┌ @ set.jl:408 Base.indexed_iterate(x, 2, _6)
│││┌ @ tuple.jl:96 x = iterate(I, state)
││││ no matching method found `iterate(::Nothing, ::Int64)`: x = iterate(I::Nothing, state::Int64)::Union{}
│││└───────────────
┌ @ /home/raf/.julia/dev/GeoInterface/src/fallbacks.jl:122 GeoInterface.error(string("Conversion is enabled for type ", T, ", but not implemented. Please report this issue t
o the package maintainer."))
│┌ @ error.jl:35 error(::String)
││ may throw: Base.throw(Base.ErrorException(s::String)::ErrorException)::Union{}
│└───────────────

```

2022-10-29 21:34 UTC, yeesian requested changes
Thank you! Can we add a unit test such that the current code will fail and the new ode will pass?

2022-11-04 08:26 UTC, rafaqz commented
Sure. (I made 4 of these PR at once analysing Rasters.jl  so writing tests was not in the time budget)

2022-11-06 10:55 UTC, rafaqz commented
Additionally, testing this is not possible with the GeoInterface test types as they have set lengths. I think they need a rethink.

2022-11-06 14:53 UTC, yeesian approved these changes
Resolving my earlier comment about having tests in lieu of https://github.com/JuliaGeo/GeoInterface.jl/pull/75#issuecomment-1304783752, thank you for the discussion!

2023-01-16 16:51 UTC, evetion commented
I'm on the fence here, is this gonna change anything, like performance or inference? Both functions work as is, and will return the same answer (like the Any[] for coordinates).

2023-01-16 17:15 UTC, rafaqz commented
It will make performance worse unfortunately. 

I haven't merge because this is really the "what to do with zero length geometries" problem and its not even clear in most specs. So maybe we wait a little.

2023-08-04 13:55 UTC, rafaqz commented
Closing as this is really the "what to do with zero length geometries" problem

2023-08-04 13:55 UTC, closed without merging